server:
  port: 8080
  servlet:
    context-path: /
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) - %clr([%t]){faint} %X{log_id} %clr(%logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p - [%t] %X{log_id} %logger{39} : %m%n%wEx"
  level:
    root: info
  file:
    path: log

## 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ppl?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
## mybatis 配置
mybatis:
  mapper-locations: classpath*:**/mybatis/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

aria2:
  url: http://72.44.78.113:6800/jsonrpc
  download:
    dir: /docker

shell:
  path: ./src/main/resources/transfer.sh

dandanplay:
  url: https://api.acplay.net/api/v2
